const fs = require('fs')
const path = require('path')
// fs.stat('./readfs.text',(err,state)=>{
//   console.log(state)
// })
// fs.access('./readfs.text',fs.constants.F_OK,(err)=>{
//   if(err) return console.log('fail')
//   console.log('success')
// })
const a = path.join('jf', 'jdj', '..')
console.log('a', a)
const b = path.join(__dirname + '/jf', 'jdj', '.')
console.log('b', b)
const c=path.resolve('/jf', 'jdj')
console.log('c', c)
const d=path.extname('./readfs.text')
console.log('d', d)
const e=path.basename('./readfs.text')
console.log('e', e)